name: task_sorter_scheduled


on:
  schedule:
    - cron: "*/20 6-23 * * *"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run task_sorter_scheduled
      env:
        
        TODOIST_APIKEY: ${{ secrets.TODOIST_APIKEY }}
      run: |
        python hospital_missing_due.py
